enable ssh

diff --git a/root/cyrilpib-init b/root/cyrilpib-init
--- a/root/cyrilpib-init
+++ b/root/cyrilpib-init
@@ -2,8 +2,13 @@ set -e
 set -u
 set -x
 
-mkdir /mnt/backup-pi-1
-echo "/dev/sda1       /mnt/backup-pi-1        btrfs   defaults,nofail 0       3"  >> /etc/fstab
+systemctl enable ssh
+systemctl start ssh
+echo "pi:$(openssl rand -base64 12)" | chpasswd
+
+mkdir -p /mnt/backup-pi-1
+grep /mnt/backup-pi-1 /etc/fstab || echo "/dev/sda1       /mnt/backup-pi-1        btrfs   defaults,nofail 0       3"  >> /etc/fstab
 
 apt-get --assume-yes install autossh python3-rpi.gpio
+
 
